SET SERVEROUT ON;
DECLARE
    -- VARIÁVEL NUMÉRICA COM 9 DIGITOS COM 2 CASAS DECIMAIS
    vVALOR1 NUMBER(11,2) := 14.5;
    
    -- VARIÁVEL NUMÉRICA COM 11 DIGITOS
    vVALOR2 NUMBER(11) := 14;
    
    -- VARIÁVEL DO TIPO CHAR (TAMANHO MÁXIMO 32767 BYTES)
    vESTADO CHAR(2) NOT NULL := 'RS';
    
    -- VARIÁVEL DO TIPO VARCHAR2 (TAMANHO MÁXIMO 32767 BYTES)
    vCIDADE VARCHAR2(40) NOT NULL := 'Porto Alegre';
    
    -- VARIÁVEL DO TIPO BOOLEAN (TRUE, FALSE E NULL)
    vVAR BOOLEAN NOT NULL := TRUE;
    
    -- VARIÁVEL DO TIPO LONG ARMAZENA UMA STRING DE CARACTERES (TAMANHO MÁXIMO 32760 BYTES)
    vTEXTO LONG := 'CAR';
    
    -- VARIÁVEL DO TIPO LONG RAW ARMAZENA DADOS BINÁRIOS (TAMANHO MÁXIMO 32760 BYTES)
    vVAR2 LONG RAW := HEXTORAW('43'||'41'||'52');
    
    -- ROWID SERVE PARA ARMAZENAR O ENDEREÇO LÓGICO DA LINHA DE UMA TABELA (VARCHAR2 COM TAMANHO MÁXIMO DE 18 CARACTERES)
    vROWID ROWID;
    
    -- DATE ARMAZENA DATAS (INICIO: 01/01/4712 AC | FIM: 31/12/9999 DC)
    vDATE DATE := SYSDATE;
    
    -- TIMESTEMP ARMAZENA A DATA COM TAMANHO MÁXIMO DE 9 DIGITOS PARA OS SEGUNDOS APÓS O DECIMAL
    vDATATIMESTEMP1 TIMESTAMP := SYSTIMESTAMP;
    vDATATIMESTEMP2 TIMESTAMP(3) := SYSTIMESTAMP; -- DEFININDO O TAMANHO MÁXIMO DOS DÍGITOS DO SEGUNDOS APÓS O DECIMAL PARA 3
    
    -- TIMESTEMP WITH TIME ZONE ARMAZENA A DATA E HORA COM A UTC CONFIGURADA PARA O BANCO DE DADOS
    vDATATIMESTEMP3 TIMESTAMP WITH TIME ZONE := SYSTIMESTAMP;
    
    -- TIMESTEMP WITH LOCAL TIME ZONE ARMAZENA A DATA E HORA COM A UTC CONFIGURADA PARA O CLIENTE
    vDATATIMESTEMP4 TIMESTAMP WITH LOCAL TIME ZONE := SYSTIMESTAMP;
    
    -- NCHAR E NVARCHAR2 ARMAZENAM CARACTERES E STRINGS UNICODE AL16UTF16 (ARMAZENA TODOS OS CARACTERES EM 2 BYTES FÍSICOS)
    -- E UTF8 (ARMAZENA TODOS OS CARACTERES EM 3 BYTES FÍSICOS)
    vESTADONCHAR NCHAR(2) := 'RS';
    vCIDADENVARCHAR2 NVARCHAR2(40) := 'Porto Alegre';
    
    -- BINARY_INTEGER ARMAZENA NÚMEROS SEM DECIMAIS INDO DE -2.147.483.648 ATÉ 2.147.483.647 (CONSUMO DE 32 BITS OU 4 BYTES)
    -- MAIS EFICIENTE QUE O TIPO NUMBER
    vVALORBINARY BINARY_INTEGER := 14;
    
    -- BINARY_FLOAT PRECISÃO SIMPLES 32 BITS
    vVALORBINARYFLOAT BINARY_FLOAT := 14.500;
    
    -- BINARY_DOUBLE PRECISÃO DUPLA 64 BITS
    vVALORBINARYDOUBLE BINARY_DOUBLE := 15.100000;
    
    -- %TYPE DECLARA UMA VARIÁVEL POR REFERÊNCIA COM O MESMO TIPO DE UMA COLUNA DO BANCO DE DADOS
    vFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE(vVALOR1);
    DBMS_OUTPUT.PUT_LINE(vVAR2);
    SELECT ROWID INTO vROWID FROM EMPLOYEES WHERE EMPLOYEE_ID = 204;
    DBMS_OUTPUT.PUT_LINE(vROWID);
    DBMS_OUTPUT.PUT_LINE(vDATATIMESTEMP3);
END;