SET SERVEROUTPUT ON;
VARIABLE gMEDIA NUMBER;

DECLARE
    vNUMERO1 NUMBER(11,2) := 2000;
    vNUMERO2 NUMBER(11,2) := 5000;
BEGIN
    :gMEDIA := (vNUMERO1 + vNUMERO2) / 2;
    DBMS_OUTPUT.PUT_LINE('MÉDIA = ' || TO_CHAR(:gMEDIA));
EXCEPTION
    WHEN OTHERS
    THEN
        DBMS_OUTPUT.PUT_LINE('ERRO ORACLE: ' || SQLCODE || SQLERRM);
END;